# Generated by Django 4.2.7 on 2023-11-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('content', models.TextField(verbose_name='Статья')),
                ('date', models.DateTimeField(verbose_name='Дата и время публикации')),
            ],
        ),
    ]
